### ISSUE TITLE
Documents are present in `analysis/` after purge

### ISSUE THREAD

**Issue by fridex** [thoth-station/purge-job#31]
**Describe the bug**

See results of the purge job stored on ocp4:

```
aws s3 s3://thoth/data/ocp4-stage/analysis/package-extract-purge                        
                           PRE package-extract-purge-2022-01-31T08:40:07.640681/
```

**To Reproduce**
1. Check documents present in ocp4 stage located in `s3://thoth/data/ocp4-stage/analysis/`
2. See `package-extract-purge-<timestamp>` is present there

**Expected behavior**

Results stored by the purge job should be present in:

```s3://thoth/data/ocp4-stage/package-extract-purge-2022-01-31T08:40:07.640681/```

See the missing `analysis` part in the prefix.

**Additional context**

It looks like the logic places results in wrong location:

https://github.com/thoth-station/storages/blob/71cdf018bda3c2245a875952dc6192828c69b41e/thoth/storages/graph/postgres.py#L7175

**Comment by mayaCostantini** [comment]
/close
The misplaced `package-extract*` documents have been moved to `s3://thoth/data/ocp4-stage/package-extract-purge-2022-01-31T08:40:07.640681/`
